---
title: "Schmidt et al. - Figure 3"
author: "Anne Hoffrichter"
date: "2024/05/16"
output: 
  bookdown::html_document2:
    code_folding: hide
    fig_caption: true
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
link-citations: yes
---

```{r loadLibraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(DESeq2)
library(patchwork)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(clusterProfiler)
library(GO.db)
library(reshape2)
```



# Figures
## A1

```{r}
my_sigGenes <- function(res, sigGeneCutOff = 0.05){
  ens.str <- substr(rownames(res), 1, 15)
  res$ENTREZ <- mapIds(org.Hs.eg.db,
                     keys=ens.str,
                     column="ENTREZID",
                     keytype="ENSEMBL",
                     multiVals="first")
  # find all significant genes
  sigGenes <- res %>% as.data.frame() %>%
    filter(padj <= sigGeneCutOff) %>%
    pull("ENTREZ") %>%
    na.exclude()
  #sigGenes <- na.exclude(sigGenes)
  sigGenes
}
```

```{r}
kk2foldchange <- function(kk){
  GO <- as.data.frame(kk@result)
  GeneRatio <- strsplit(GO$GeneRatio,"/")
  GRdf <- data.frame()
  for (i in seq_along(GeneRatio)){
    GRdf[i,1] <- GeneRatio[[i]][1]
    GRdf[i,2] <- GeneRatio[[i]][2]
  }
  GRdf$V1 <- as.numeric(GRdf$V1)
  GRdf$V2 <- as.numeric(GRdf$V2)
  GO$GeneRatio2 <- GRdf$V1/GRdf$V2
  BgRatio <- strsplit(GO$BgRatio,"/")
  BgRdf <- data.frame()
  for (i in seq_along(BgRatio)){
    BgRdf[i,1] <- BgRatio[[i]][1]
    BgRdf[i,2] <- BgRatio[[i]][2]
  }
  BgRdf$V1 <- as.numeric(BgRdf$V1)
  BgRdf$V2 <- as.numeric(BgRdf$V2)
  GO$BgRatio2 <- BgRdf$V1/BgRdf$V2
  GO$foldchange <- GO$GeneRatio2/GO$BgRatio2
  return(GO)
}
```

```{r}
dds <- readRDS("../data/001_dds.rds")
```

```{r}
res <- results(dds, contrast = c("Condition_simple", "Trt5", "Ctrl"), alpha = 0.05)
res$gene_symbol <- mcols(dds)$gene_symbol
```

```{r}
sigGenes <- my_sigGenes(res)
```

```{r}
TOI1 <- c("axonogenesis", "synapse organization", "regulation of trans-synaptic signaling","modulation of chemical synaptic transmission", "growth cone", "distal axon", "synaptic vesicle", "synaptic membrane", "neuron to neuron synapse", "neuron spine", "dendritic spine", "presynaptic active zone", "postsynaptic density", "glutamatergic synapse")
```

```{r}
kk <- enrichGO(gene = sigGenes, ont="ALL", OrgDb = "org.Hs.eg.db")
GO <- kk2foldchange(kk)
GOsub <- filter(GO, Description %in% TOI1) 
GO_ordered <- GOsub[match(TOI1,GOsub$Description),]
GO_ordered$foldchange <- as.numeric(GO_ordered$foldchange)
GO_ordered <- na.omit(GO_ordered)
GO_ordered$Description<- factor(GO_ordered$Description, levels = rev(GO_ordered$Description))
```

```{r}
TOI2 <- c("Neurotrophin signaling pathway", "Axon guidance", "Synaptic vesicle cycle")
```

```{r}
kk <- enrichKEGG(gene = sigGenes, organism = "hsa")
KEGG <- kk2foldchange(kk)
KEGGsub <- filter(KEGG, Description %in% TOI2) 
KEGG_ordered <- KEGGsub[match(KEGGsub$Description, TOI2),]
KEGG_ordered$foldchange <- as.numeric(KEGG_ordered$foldchange)
KEGG_ordered$Description<- factor(KEGG_ordered$Description, levels = rev(KEGG_ordered$Description))
KEGG_ordered$ONTOLOGY <- "KEGG"

GO_KEGG <- rbind(GO_ordered[,c(1,3,7,13)], KEGG_ordered[,c(13,2,6,12)])
GO_KEGG$Description <- stringr::str_wrap(GO_KEGG$Description, 40)
GO_KEGG$Description<- factor(GO_KEGG$Description, levels = rev(GO_KEGG$Description))
```


```{r,fig.asp=1.05, fig.width=10.2}
(FigA1 <- ggplot(GO_KEGG, aes(foldchange, factor(Description,levels = rev(Description)))) +
   facet_grid(ONTOLOGY~.,scales = "free", space = "free")+
   geom_col(aes(fill=p.adjust))+
   theme_minimal(base_size = 20)+
   xlab("fold enrichment")+
   ylab("")+
   labs(fill = "p.adjust")+
   ggtitle("Ctrl vs. 1d Psi")+
   theme(
    title=element_text(size=14),
    axis.text = element_text(size=20, color="black"),
    axis.title.x = element_text(size=18),
    legend.text = element_text(size=16),
    legend.title = element_text(size=16)
    )
 )
```

## A2

```{r}
res <- results(dds, contrast = c("Condition_simple", "Trt3", "Ctrl"), alpha = 0.05)
res$gene_symbol <- mcols(dds)$gene_symbol
```

```{r}
sigGenes <- my_sigGenes(res)
```

```{r}
TOI1 <- c( "axonogenesis","synapse organization", "growth cone", "distal axon", "presynaptic active zone","postsynaptic density", "glutamatergic synapse")
```

```{r}
kk <- enrichGO(gene = sigGenes, ont="ALL", OrgDb = "org.Hs.eg.db", pvalueCutoff = 1, qvalueCutoff = 0.9)
GO <- kk2foldchange(kk)
GOsub <- filter(GO, Description %in% TOI1) 
GO_ordered <- GOsub[match(TOI1,GOsub$Description),]
GO_ordered$foldchange <- as.numeric(GO_ordered$foldchange)
GO_ordered <- na.omit(GO_ordered)
GO_ordered$Description<- factor(GO_ordered$Description, levels = rev(GO_ordered$Description))
```

```{r}
TOI2 <- c("Synaptic vesicle cycle")
```

```{r}
kk <- enrichKEGG(gene = sigGenes, organism = "hsa")
KEGG <- kk2foldchange(kk)
KEGGsub <- filter(KEGG, Description %in% TOI2) 
KEGG_ordered <- KEGGsub[match(KEGGsub$Description, TOI2),]
KEGG_ordered$foldchange <- as.numeric(KEGG_ordered$foldchange)
KEGG_ordered$Description<- factor(KEGG_ordered$Description, levels = rev(KEGG_ordered$Description))
KEGG_ordered$ONTOLOGY <- "KEGG"

GO_KEGG <- rbind(GO_ordered[,c(1,3,7,13)], KEGG_ordered[,c(13,2,6,12)])
GO_KEGG$Description <- stringr::str_wrap(GO_KEGG$Description, 40)
GO_KEGG$Description<- factor(GO_KEGG$Description, levels = rev(GO_KEGG$Description))
```

```{r,fig.asp=0.62, fig.width=10.2}
(FigA2 <- ggplot(GO_KEGG, aes(foldchange, factor(Description,levels = rev(Description)))) +
   facet_grid(ONTOLOGY~.,scales = "free", space = "free")+
   geom_col(aes(fill=p.adjust))+
   theme_minimal(base_size = 20)+
   xlab("fold enrichment")+
   ylab("")+
   labs(fill = "p.adjust")+
   ggtitle("Ctrl vs. 3d Psi")+
   theme(
    title=element_text(size=14),
    axis.text = element_text(size=20, color="black"),
    axis.title.x = element_text(size=18),
    legend.text = element_text(size=16),
    legend.title = element_text(size=16),
    plot.margin = margin(10,10,10,120)
    )
 )
```

## Fig. 3B
### ctrl vs 1dPsi

```{r}
my_GO <- function(res, sigGenes = sigGenes, ont=NULL){
  kk <- enrichGO(gene = sigGenes, ont=ont, OrgDb = "org.Hs.eg.db")
  if(is.null(kk)){
    print(paste0("No enriched GO terms for ", ont))
    }else{
      GO <- kk2foldchange(kk)
      }
  return(list(GO))
}
```

```{r}
GO_all_ont <- function(.res, comparison, .sigGenes=sigGenes){
  p1 <- my_GO(.res,sigGenes, ont = "BP")
  p2 <- my_GO(.res, sigGenes, ont = "MF")
  p3 <- my_GO(.res, sigGenes, ont = "CC")
  list(p1,p2,p3)
}
```

```{r}
# R & package versions used in the manuscript: R version 4.2.2, AnnotationDbi_1.60.2, GO.db_3.16.0, org.Hs.eg.db_3.16.0
GO_genes <- function(GO_term){
  go_id = GOID(GOTERM[Term(GOTERM) == GO_term])
    allegs <- get(go_id, org.Hs.egGO2ALLEGS)
    genes <- unlist(mget(allegs, org.Hs.egSYMBOL))
    genes <- unique(genes)
    genes
}
```

```{r}
my_GO_dat_bulk <- function (terms, genes) 
{
    colnames(terms) <- tolower(colnames(terms))
    terms$genes <- toupper(terms$genes)
    genes$ID <- toupper(genes$ID)
    tgenes <- strsplit(as.vector(terms$genes), ", ")
    if (length(tgenes[[1]]) == 1) 
        tgenes <- strsplit(as.vector(terms$genes), ",")
    count <- sapply(1:length(tgenes), function(x) length(tgenes[[x]]))
    logFC <- sapply(unlist(tgenes), function(x) genes$log2FoldChange[match(x, 
        genes$ID)])
    if (class(logFC) == "factor") {
        logFC <- gsub(",", ".", gsub("\\.", "", logFC))
        logFC <- as.numeric(logFC)
    }
    s <- 1
    zsc <- c()
    for (c in 1:length(count)) {
        value <- 0
        e <- s + count[c] - 1
        value <- sapply(logFC[s:e], function(x) ifelse(x > 0, 
            1, -1))
        value <- na.omit(value)
        zsc <- c(zsc, sum(value)/sqrt(count[c]))
        s <- e + 1
    }
    if (is.null(terms$id)) {
        df <- data.frame(category = rep(as.character(terms$category), 
            count), term = rep(as.character(terms$description), count), 
            count = rep(count, count), genes = as.character(unlist(tgenes)), 
            logFC = logFC, adj_pval = rep(terms$p.adjust, count), 
            zscore = rep(zsc, count), stringsAsFactors = FALSE)
    }
    else {
        df <- data.frame(category = rep(as.character(terms$category), 
            count), ID = rep(as.character(terms$id), count), 
            term = rep(as.character(terms$description), count), count = rep(count, 
                count), genes = as.character(unlist(tgenes)), 
            logFC = logFC, adj_pval = rep(terms$p.adjust, count), 
            zscore = rep(zsc, count), stringsAsFactors = FALSE)
    }
    return(df)
}
```

```{r}
res <- results(dds, contrast = c("Condition_simple", "Trt5", "Ctrl"), alpha = 0.05)
res$gene_symbol <- mcols(dds)$gene_symbol
```

```{r}
sigGenes <- my_sigGenes(res)
```

```{r}
TOI <- c("axonogenesis", "growth cone", "presynaptic active zone", "postsynaptic density", "glutamatergic synapse","synapse organization")
```

```{r, fig.asp=1.5}
# comparison = "Ctrl vs. 1d Psi"
l <- GO_all_ont(res)
```

```{r}
sig_genes <- as.data.frame(res) %>% filter(padj<0.05 & ! is.na(padj))
colnames(sig_genes)[7] <- "ID"
```

```{r}
GO <- bind_rows(BP=l[[1]][[1]], MF=l[[2]][[1]], CC=l[[3]][[1]], .id="Category")
GO_Ctrl_vs_1d <- GO
GO <- filter(GO, Description %in% TOI)
GO$Genes <- map(GO$Description, GO_genes)
GO$Genes <- map(GO$Genes, ~paste(.x, collapse=", "))
GO$Genes <- unlist(GO$Genes)
```

```{r}
GO_dat <- my_GO_dat_bulk(GO, sig_genes)
```

```{r}
GO_dat2 <- filter(GO_dat, !is.na(logFC))
t <- table(GO_dat2$term)
for(i in seq_along(GO_dat2$term)){
    GO_dat2$count[i] <- t[match(GO_dat2$term[i], names(t))]
}

```

```{r}
GO_dat3 <- filter(GO_dat2, term %in% TOI)
GO_dat3$updown <- ifelse(GO_dat3$logFC<0, "downregulated", "upregulated")
```

```{r}
a <- 
  ggplot(GO_dat3, aes(x=ID, y=logFC, color=updown))+
  geom_jitter(width=0.2)+
  geom_vline(xintercept=c(1.5,2.5,3.5, 4.5,5.5))+
  geom_hline(yintercept=0, linetype="dashed")+
  theme_classic()+
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        axis.ticks.x = element_blank(), 
        legend.text=element_text(size=6), 
        axis.title.y = element_text(margin = margin(r = 0, unit = "pt"), size=16),
        axis.text.y = element_text(size=14, color="black"))+
  scale_fill_discrete(labels=c("downregulated", "upregulated"))
```

```{r}
bars <- GO_dat3[!duplicated(GO_dat3$term), ]
b <- ggplot(bars, aes(x=ID, y=zscore))+
  geom_col(aes(fill=zscore))+
  scale_fill_gradient(low = "white", high = "#00BFC4", limits=c(0, 3))+
  theme_void()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 14), 
        axis.title.x = element_blank(),
        legend.title = element_text( size=14), 
        legend.text=element_text(size=10))
```

```{r}
bars <- bars[order(bars$ID),]
c <- gridExtra::tableGrob(bars[, c("ID", "term")], rows=NULL,theme=gridExtra::ttheme_default(base_size=14))
```

```{r, fig.asp=0.61, fig.width=8.8}

(Fig3D1 <- wrap_elements(a+c+b+guide_area()+ 
                           plot_layout(guides="collect", heights = c(2,1))+
                           plot_annotation(title="Ctrl vs. 1d Psi")& 
                           guides(colour = guide_legend(override.aes = list(size=4))) &
                           theme(legend.position = "right", legend.direction="horizontal",
                                 legend.text = element_text(size=14),
                                 legend.key.size = unit(20, "pt"),
                                 legend.box.margin = margin(t = 1, unit = "in"),
                                 plot.title = element_text(size=15))))
```

### ctrl vs 3d psi

```{r}
res <- results(dds, contrast = c("Condition_simple", "Trt3", "Ctrl"), alpha = 0.05)
res$gene_symbol <- mcols(dds)$gene_symbol
```

```{r}
sigGenes <- my_sigGenes(res)
```

```{r}
TOI <- c("axonogenesis", "growth cone", "presynaptic active zone", "postsynaptic density", "glutamatergic synapse",  "synapse organization")
```

```{r, fig.asp=1.5}
l <- GO_all_ont(res)
```

```{r}
sig_genes <- as.data.frame(res) %>% filter(padj<0.05 & ! is.na(padj))
colnames(sig_genes)[7] <- "ID"
```

```{r}
GO <- bind_rows(BP=l[[1]][[1]], MF=l[[2]][[1]], CC=l[[3]][[1]], .id="Category")
GO_Ctrl_vs_3d <- GO
GO <- filter(GO, Description %in% TOI)
GO$Genes <- map(GO$Description, GO_genes)
GO$Genes <- map(GO$Genes, ~paste(.x, collapse=", "))
GO$Genes <- unlist(GO$Genes)
```

```{r}
GO_dat <- my_GO_dat_bulk(GO, sig_genes)
```

```{r}
GO_dat2 <- filter(GO_dat, !is.na(logFC))
t <- table(GO_dat2$term)
for(i in seq_along(GO_dat2$term)){
    GO_dat2$count[i] <- t[match(GO_dat2$term[i], names(t))]
}

```

```{r}
GO_dat3 <- filter(GO_dat2, term %in% TOI)
GO_dat3$updown <- ifelse(GO_dat3$logFC<0, "downregulated", "upregulated")
```

```{r}
a <- 
  ggplot(GO_dat3, aes(x=ID, y=logFC, color=updown))+
  geom_jitter(width=0.2)+
  geom_vline(xintercept=c(1.5,2.5,3.5, 4.5,5.5))+
  geom_hline(yintercept=0, linetype="dashed")+
  theme_classic()+
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        axis.ticks.x = element_blank(), 
        legend.text=element_text(size=6), 
        axis.title.y = element_text(margin = margin(r = 0, unit = "pt"), size=16),
        axis.text.y = element_text(size=14, color="black"))+
  scale_fill_discrete(labels=c("downregulated", "upregulated"))
```

```{r}
bars <- GO_dat3[!duplicated(GO_dat3$term), ]
b <- ggplot(bars, aes(x=ID, y=zscore))+
  geom_col(aes(fill=zscore))+
  scale_fill_gradient(low = "white", high = "#00BFC4", limits=c(0, 3))+
  theme_void()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 14), 
        axis.title.x = element_blank(),
        legend.title = element_text( size=14), 
        legend.text=element_text(size=10))
```

```{r}
bars <- bars[order(bars$ID),]
c <- gridExtra::tableGrob(bars[, c("ID", "term")], rows=NULL,theme=gridExtra::ttheme_default(base_size=14))
```

```{r, fig.asp=0.61, fig.width=8.8}
(Fig3D2 <- wrap_elements(a+c+b+guide_area()+ 
                           plot_layout(guides="collect", heights = c(2,1))+
                           plot_annotation(title="Ctrl vs. 3d Psi")& 
                           guides(colour = guide_legend(override.aes = list(size=4))) &
                           theme(legend.position = "right", legend.direction="horizontal",
                                 legend.text = element_text(size=14),
                                 legend.key.size = unit(20, "pt"),
                                 legend.box.margin = margin(t = 1, unit = "in"),
                                 plot.title = element_text(size=15))))
```

## Fig. 3C

```{r}
GO_smooth_line_plot <- function(TPM, genes){
  mat <- TPM[,!names(TPM)%in% c("gene_name")]
  gene_symbol <-rownames(mat)
  names(gene_symbol) <-  TPM$gene_name
  df <- t(mat[gene_symbol[genes], ]) 
  colnames(df) <- c(genes)
  df <- as.data.frame(df)
  all_na <- function(x) any(!is.na(x))
  df <- df %>% select_if(all_na)
  rowm <- rowMeans(df)
  names(rowm) <- c(rep("Ctrl", times=8), rep("3d", times=8), rep("1d", times=7))
  rowm <- as.data.frame(rowm)
  rowm$group <- c(rep("Ctrl", times=8), rep("3d", times=8), rep("1d", times=7))
  #rowm$group_sample <- c(colnames(ncounts)[1:8], paste0("psi", 1:8), paste0("PLG", 1:4), paste0("psi_PLG", 1:4))
  p <- mutate(rowm, group=factor(group,ordered=T, c("Ctrl", "1d", "3d")))
  y <- aggregate(p[, 1], list(p$group), mean)
  se <- aggregate(p[, 1], list(p$group), sd)

  df <- data.frame(group=ordered(c("Ctrl", "1d", "3d"), levels=c("Ctrl", "1d", "3d")), TPM=y$x, se=se$x)
  print(
    ggplot(NULL,  aes(x= as.numeric(group)))+ 
      geom_smooth(data=df, aes(as.numeric(group), TPM, ymin = TPM - se, ymax = TPM + se), stat="identity", col="red")+
      scale_x_discrete(limits=c("Ctrl", "1d", "3d")) +
      scale_y_log10()+ 
      theme_classic(base_size = 24)+
      theme(legend.title=element_blank(), axis.title.x = element_blank(), axis.text = element_text(size=30), axis.title.y = element_text(size=30))+
      ylab("TPM")+
      coord_cartesian(xlim = c(1,3.2), expand = FALSE)
  )
}
```

```{r}
TPM <- readRDS("../data/001_TPM.rds")
TPM_ctrl_1d_3d_Psi <- TPM[,c(1:8,9:16,24:30,44)]
```

```{r}
GOs <- c("axonogenesis", "growth cone", "synapse organization", "presynaptic active zone", "postsynaptic density", "glutamatergic synapse")
```

```{r, include=FALSE}
plots <- list()
for(i in seq_along(GOs)){
  genes <- GO_genes(GOs[i])
  plots[[i]] <- GO_smooth_line_plot(TPM_ctrl_1d_3d_Psi, genes)+
  ggtitle(GOs[i])
}
```

```{r, fig.width=24, fig.asp=0.6}
plots[[1]] <- plots[[1]]+ 
  theme(plot.margin = margin(50,0,20,0))
plots[[2]] <- plots[[2]]+
  theme(axis.title.y = element_blank(), 
        plot.margin = margin(50,0,20,0))
plots[[3]] <- plots[[3]]+
  theme(axis.title.y = element_blank(), 
        plot.margin = margin(50,0,20,0))
plots[[4]] <- plots[[4]]+ 
  theme(plot.margin = margin(20,0,50,0))
plots[[5]] <- plots[[5]]+
  theme(axis.title.y = element_blank(), 
        plot.margin = margin(20,0,50,0))
plots[[6]] <- plots[[6]]+
  theme(axis.title.y = element_blank(), 
        plot.margin = margin(20,0,50,0))
Fig3C <- (plots[[1]]|plots[[2]]|plots[[3]])/(plots[[4]]|plots[[5]]|plots[[6]])
```


```{r}
Fig3C[[1]][[3]]$labels$title <- str_wrap(Fig3C[[1]][[3]]$labels$title, width = 12)
Fig3C[[2]][[1]]$labels$title <- str_wrap(Fig3C[[2]][[1]]$labels$title, width = 12)
Fig3C[[2]][[2]]$labels$title <- str_wrap(Fig3C[[2]][[2]]$labels$title, width = 12)
Fig3C[[2]][[3]]$labels$title <- str_wrap(Fig3C[[2]][[3]]$labels$title, width = 12)

Fig3C[[1]][[1]]$theme$axis.title.y$size <- 18
Fig3C[[2]][[1]]$theme$axis.title.y$size <- 18
```

R & package versions used in the manuscript: R version 4.2.2, AnnotationDbi_1.60.2, GO.db_3.16.0, org.Hs.eg.db_3.16.0

```{r, fig.asp=0.72,fig.width=8.8}
Fig3C&
  scale_x_discrete(limits=c("Ctrl", "1d Psi", "3d Psi"))&
  coord_cartesian(xlim = c(1,3.1), expand = FALSE)&
  theme(plot.margin = margin(10,10,10,10),
        axis.text = element_text(size=18, color="black"),
        axis.text.x = element_text(angle = 45, hjust=1,vjust=1),
        title=element_text(size=16))
```

##  Fig. 3D


```{r}
GO_terms <-  c("axonogenesis", "growth cone", "synapse organization", "presynaptic active zone", "postsynaptic density", "glutamatergic synapse")
```

```{r}
my_circle_dat <- function (terms, genes) 
{
    colnames(terms) <- tolower(colnames(terms))
    terms$genes <- toupper(terms$genes)
    genes$ID <- toupper(genes$ID)
    tgenes <- strsplit(as.vector(terms$genes), ", ")
    if (length(tgenes[[1]]) == 1) 
        tgenes <- strsplit(as.vector(terms$genes), ",")
    count <- sapply(1:length(tgenes), function(x) length(tgenes[[x]]))
    logFC <- sapply(unlist(tgenes), function(x) genes$logFC[match(x, 
        genes$ID)])
    if (class(logFC) == "factor") {
        logFC <- gsub(",", ".", gsub("\\.", "", logFC))
        logFC <- as.numeric(logFC)
    }
    s <- 1
    zsc <- c()
    for (c in 1:length(count)) {
        value <- 0
        e <- s + count[c] - 1
        value <- sapply(logFC[s:e], function(x) ifelse(x > 0, 
            1, -1))
        value <- na.omit(value)
        zsc <- c(zsc, sum(value)/sqrt(count[c]))
        s <- e + 1
    }
    if (is.null(terms$id)) {
        df <- data.frame(category = rep(as.character(terms$category), 
            count), term = rep(as.character(terms$term), count), 
            count = rep(count, count), genes = as.character(unlist(tgenes)), 
            logFC = logFC, adj_pval = rep(terms$adj_pval, count), 
            zscore = rep(zsc, count), stringsAsFactors = FALSE)
    }
    else {
        df <- data.frame(category = rep(as.character(terms$category), 
            count), ID = rep(as.character(terms$id), count), 
            term = rep(as.character(terms$term), count), count = rep(count, 
                count), genes = as.character(unlist(tgenes)), 
            logFC = logFC, adj_pval = rep(terms$adj_pval, count), 
            zscore = rep(zsc, count), stringsAsFactors = FALSE)
    }
    return(df)
}
```

```{r}
res1d <- results(dds, contrast = c("Condition_simple", "Trt5", "Ctrl"), alpha = 0.05)
res1d$gene_symbol <- mcols(dds)$gene_symbol
genes1d <- as.data.frame(res1d)
```

```{r}
sigGenes <- my_sigGenes(res1d)
```

```{r, fig.asp=1.5}
l <- GO_all_ont(res1d, comparison = "Ctrl vs. Trt5")
```

```{r}
GO1d_BP <- l[[1]][[1]]
GO1d_MF <- l[[2]][[1]]
GO1d_CC <- l[[3]][[1]]
GO1d <- bind_rows(BP=GO1d_BP, MF=GO1d_MF, CC=GO1d_CC, .id="Category")
colnames(GO1d)[3] <- "Term"
colnames(GO1d)[7] <- "adj_pval"
# colnames(GO[9]) <- "genes"
colnames(genes1d)[2] <- "logFC"
colnames(genes1d)[7] <- "ID"
colnames(GO1d)[13] <- "logFC"
colnames(genes1d)[1] <- "AveExpr"
colnames(genes1d)[5] <- "P.Value"
colnames(genes1d)[6] <- "adj.P.Val"
```

```{r}
GO1d <- filter(GO1d, Term %in% GO_terms)
GO1d$Genes <- map(GO1d$Term, GO_genes)
GO1d$Genes <- map(GO1d$Genes, ~paste(.x, collapse=", "))
GO1d$Genes <- unlist(GO1d$Genes)
```

```{r}
res3d <- results(dds, contrast = c("Condition_simple", "Trt3", "Ctrl"), alpha = 0.05)
res3d$gene_symbol <- mcols(dds)$gene_symbol
genes3d <- as.data.frame(res3d)
```

```{r}
sigGenes <- my_sigGenes(res3d)
```

```{r, fig.asp=1.5}
l <- GO_all_ont(res3d, comparison = "Ctrl vs. Trt5")
```

```{r}
GO3d_BP <- l[[1]][[1]]
GO3d_MF <- l[[2]][[1]]
GO3d_CC <- l[[3]][[1]]
GO3d <- bind_rows(BP=GO3d_BP, MF=GO3d_MF, CC=GO3d_CC, .id="Category")
colnames(GO3d)[3] <- "Term"
colnames(GO3d)[7] <- "adj_pval"
# colnames(GO[9]) <- "genes"
colnames(genes3d)[2] <- "logFC"
colnames(genes3d)[7] <- "ID"
colnames(GO3d)[13] <- "logFC"
colnames(genes3d)[1] <- "AveExpr"
colnames(genes3d)[5] <- "P.Value"
colnames(genes3d)[6] <- "adj.P.Val"
```

```{r}
GO3d <- filter(GO3d, Term %in% GO_terms)
GO3d$Genes <- map(GO3d$Term, GO_genes)
GO3d$Genes <- map(GO3d$Genes, ~paste(.x, collapse=", "))
GO3d$Genes <- unlist(GO3d$Genes)
```

```{r}
circ <- my_circle_dat(GO1d, genes1d)
circ <- filter(circ, !is.na(logFC))
```

```{r}
chord <- GOplot::chord_dat(circ, process= GO_terms)
chord <- cbind(chord,circ$logFC[match(rownames(chord), circ$genes)])
colnames(chord)[7] <- "logFC"

```

```{r}
sig_genes1d <- filter(genes1d, adj.P.Val<0.05& ! is.na(adj.P.Val))
```

```{r}
chord <- chord[rownames(chord) %in% sig_genes1d$ID,]
```

Minimum appearance of a significant gene (Ctrl vs 1d Psi) in 4 GO terms:

```{r, fig.width=6.45, fig.asp=0.8, dev="svg"}
Fig3D1 <- GOplot::GOChord(chord, 
                          space = 0.01, 
                          gene.order = 'logFC', 
                          gene.space = 0.35, 
                          gene.size = 5, 
                          limit=c(4,1), 
                          lfc.min=-1, 
                          lfc.max=2)+
  ggtitle("Ctrl vs. 1d Psi")
Fig3D1$guides$size$ncol <- 3
(Fig3D1 <- Fig3D1+ 
      theme(plot.margin = margin(10,10,10,10), 
          plot.title = element_text(hjust = 0.5, size=0),
          legend.text  = element_text(size=18), 
          legend.position = "none")+
    coord_fixed(clip="off"))
```

```{r}
circ <- my_circle_dat(GO3d, genes3d)
circ <- filter(circ, !is.na(logFC))
```

```{r}
chord <- GOplot::chord_dat(circ, process= GO_terms)
chord <- cbind(chord,circ$logFC[match(rownames(chord), circ$genes)])
colnames(chord)[7] <- "logFC"

```

```{r}
sig_genes3d <- filter(genes3d, adj.P.Val<0.05& ! is.na(adj.P.Val))
```

```{r}
chord <- chord[rownames(chord) %in% sig_genes3d$ID,]
```

Minimum appearance of a significant gene (Ctrl vs 3d Psi) in 4 GO terms:

```{r, fig.width=20, fig.asp=1}
Fig3D2 <- GOplot::GOChord(chord,
                          space = 0.01, 
                          gene.order = 'logFC', 
                          gene.space = 0.35, 
                          gene.size = 5, 
                          limit=c(3,1))+
  ggtitle("Ctrl vs. 3d Psi")
Fig3D2$guides$size$ncol <- 3
```

```{r, fig.width=6.45, fig.asp=0.8, dev="svg"}
(Fig3D2 <- Fig3D2+ 
      theme(plot.margin = margin(10,10,10,10), 
          plot.title = element_text(hjust = 0.5, size=0),
          legend.text  = element_text(size=18), 
          legend.position = "none")+
    coord_fixed(clip="off"))
```

## Fig. 3E

```{r}
significance_of_genes <- function(genes, res_d1, res_d3){
  df <- data.frame(genes=genes)
  for(i in seq_along(genes)){
    temp <- filter(res_d1, gene_symbol==genes[i])
      if(is.null(temp$padj)){
          df$d1[i] <- "NA"
      } else if(length(temp$padj)==0){
          df$d1[i] <- "ns"
      } else if(temp$padj<=0.001){
          df$d1[i] <- "***"
      } else if(temp$padj<=0.01){
          df$d1[i] <- "**"
      } else if(temp$padj<=0.05){
          df$d1[i] <- "*"
      } else {
          df$d1[i] <- "ns"
      }
  }

  for(i in seq_along(genes)){
    temp <- filter(res_d3, gene_symbol==genes[i])
      if(is.null(temp$padj)){
          df$d3[i] <- "NA"
      } else if(length(temp$padj)==0){
          df$d3[i] <- "ns"
      } else if(temp$padj<=0.001){
        df$d3[i] <- "***"
    } else if(temp$padj<=0.01){
        df$d3[i] <- "**"
    } else if(temp$padj<=0.05){
        df$d3[i] <- "*"
    } else {
        df$d3[i] <- "ns"
    }
  }
  return(df)
}
```

```{r}
ncounts_GO <- function(dds, genes){
  ncounts1 <- dds[dds@rowRanges@elementMetadata@listData[["gene_symbol"]] %in% genes]
  ncounts <- counts(ncounts1, normalize=T)
  rownames(ncounts) <- ncounts1@rowRanges@elementMetadata@listData[["gene_symbol"]]
  colnames(ncounts) <- c(rep("Ctrl", times=8), rep("3d", times=8), rep("1d", times=7))
  ncounts <- ncounts[match(genes, rownames(ncounts)),]
  ncounts <- na.omit(ncounts)
  return(ncounts)
}
```


```{r}
heatmap_sample_mean_Ctrl_d1 <- function(ncounts, breaks=c(-1,0,1)){
  Ctrl <- rowMeans(ncounts[,1:8])
  #d3 <- rowMeans(ncounts[,9:16])
  d1 <- rowMeans(ncounts[,17:23])
  av_ncounts <- cbind(Ctrl, d1)
  zcounts <- my_zscale(av_ncounts)
  lims <- c(min(zcounts$value), max(zcounts$value)) %>% abs()%>% max()
  levels <- filter(zcounts[order(zcounts$value),], Var2=="Ctrl")$Var1
  ggplot(data = zcounts, aes(x=Var2, y=Var1, fill=value)) +
    geom_tile()+
    scale_fill_viridis_c(option="viridis", limits = c(-lims,lims), breaks=breaks)+
    scale_y_discrete(limits = rev(levels), position = "right")+
    theme_minimal(base_size=12)+
    labs(fill="Z-Score", x="", y="")+
    theme(axis.text.x = element_text(angle = 90, vjust=0.5,size=14), 
          axis.text.y = element_text(face = "italic",size=14), 
          legend.position="left", 
          legend.key.width = unit(0.8,"cm"),
          plot.title = element_text(size=14,hjust = 0.5))
}

heatmap_sample_mean <- function(ncounts, breaks=c(-1,0,1)){
  Ctrl <- rowMeans(ncounts[,1:8])
  d3 <- rowMeans(ncounts[,9:16])
  d1 <- rowMeans(ncounts[,17:23])
  av_ncounts <- cbind(Ctrl, d1,d3)
  zcounts <- my_zscale(av_ncounts)
  lims <- c(min(zcounts$value), max(zcounts$value)) %>% abs()%>% max()
  levels <- filter(zcounts[order(zcounts$value),], Var2=="Ctrl")$Var1
  ggplot(data = zcounts, aes(x=Var2, y=Var1, fill=value)) +
    geom_tile()+
    scale_fill_viridis_c(option="viridis", limits = c(-lims,lims), breaks=breaks)+
    scale_y_discrete(limits = rev(levels), position = "right")+
    theme_minimal(base_size=12)+
    labs(fill="Z-Score", x="", y="")+
    theme(axis.text.x = element_text(angle = 90, vjust=0.5,size=14),
          axis.text.y = element_text(face = "italic",size=14),
          legend.position="left",
          legend.key.width = unit(0.8,"cm"),
          plot.title = element_text(size=14,hjust = 0.5))
}
```

```{r}
my_zscale <- function(x){
  M <- rowMeans(x, na.rm = TRUE)
  nsamples <- ncol(x)
  DF <- nsamples - 1L
  IsNA <- is.na(x)
  if (any(IsNA)) {
    mode(IsNA) <- "integer"
    DF <- DF - rowSums(IsNA)
    DF[DF == 0L] <- 1L
  }
  x <- x - M
  V <- rowSums(x^2L, na.rm = TRUE)/DF
  x <- x/sqrt(V + 0.01)
  out <- melt(x)
  out
}
```

```{r}
dds <- readRDS("../data/001_dds.rds")
dds <- dds[,c(1:16, 24:30)]
dds$Condition_simple <- droplevels(dds$Condition_simple)
```

```{r, fig.asp=6,fig.width=6}
res_d1 <- results(dds, contrast = c("Condition_simple", "Trt5", "Ctrl"), alpha = 0.05)
res_d1$gene_symbol <- mcols(dds)$gene_symbol
res_d1 <- as.data.frame(res_d1) %>% filter(padj<=0.05)
res_d3 <- results(dds, contrast = c("Condition_simple", "Trt3", "Ctrl"), alpha = 0.05)
res_d3$gene_symbol <- mcols(dds)$gene_symbol
res_d3 <- as.data.frame(res_d3) %>% filter(padj<=0.05)

sig_genes <- unique(res_d1$gene_symbol, res_d3$gene_symbol)
```

```{r}
genes <- c("FOS","FOSB", "FOSL1", "FOSL2", "JUNB", "JUND", "JUN", "EGR1", "EGR2", "ARC")
```

```{r}
df <- significance_of_genes(genes, res_d1, res_d3)
```

```{r, fig.asp=1.1, fig.width=4.4}
ncounts <- ncounts_GO(dds, genes)
```

```{r, fig.asp=1.1, fig.width=4.4}
(Fig3E1 <- heatmap_sample_mean_Ctrl_d1(ncounts, breaks=c(-0.5,0,0.5))+
  shadowtext::geom_shadowtext(
     aes(label=paste(c(rep("",times=length(genes)),df$d1))),
     y=c(rep(df$genes, times=2)),
     x=rep(c(1,2), each=length(genes)),
     bg.color="white", bg.r=0.1, color = "black", size=5)+
  ggtitle("Immediate early genes")+
    scale_x_discrete(labels=c("Ctrl", "1d Psi"))+
    theme(axis.text = element_text(color="black"),
          axis.text.x = element_text(angle = 0),
          plot.title=element_text(size=18),
          legend.text = element_text(size=12)))
```

```{r}
genes <- c("GRIN1", "GRIN2A", "GRIN2B", "GRIN2C", "GRIN2D", "GRIN3A", "GRIN3B", "GRIA1", "GRIA2", "GRIA3", "GRIA4")
```

```{r}
df <- significance_of_genes(genes, res_d1, res_d3)
```

```{r, fig.asp=1.1, fig.width=4.4}
ncounts <- ncounts_GO(dds, genes)
```

```{r, fig.asp=1.1, fig.width=4.4}
(Fig3E2 <- heatmap_sample_mean(ncounts, breaks=c(-0.5,0,0.5))+
  shadowtext::geom_shadowtext(
     aes(label=paste(c(rep("",times=length(genes)),df$d1, df$d3))),
     y=c(rep(df$genes, times=3)),
     x=rep(c(1,2,3), each=length(genes)),
     bg.color="white", bg.r=0.1, color = "black", size=5)+
  ggtitle("Genes of interest")+
    scale_x_discrete(labels=c("Ctrl", "1d Psi", "3d Psi"))+
    theme(axis.text = element_text(color="black"),
          axis.text.x = element_text(angle = 0),
          plot.title=element_text(size=18),
          legend.text = element_text(size=12)))
```

## Fig. 3F


```{r}
TPM <- readRDS("../data/001_TPM.rds")
TPM <- TPM[,c(1:35)]
```

```{r}
res <- results(dds, contrast = c("Condition_simple", "Trt3", "Ctrl"), alpha = 0.05)
sigGenes_up <- res %>% as.data.frame() %>% filter(padj<0.05) %>% 
  filter(log2FoldChange>0) %>% rownames() %>% substr(1, 15)
```

Number of genes: `r length(sigGenes_up)`

```{r}

GO_smooth_line_plot_3d <- function(TPM, genes){
  mat <- TPM[,!names(TPM)%in% c("gene_name")]
  gene_symbol <-rownames(mat)
  names(gene_symbol) <-  TPM$gene_name
  df <- t(mat[genes, ]) 
  colnames(df) <- c(genes)
  df <- as.data.frame(df)
  all_na <- function(x) any(!is.na(x))
  df <- df %>% select_if(all_na)
  rowm <- rowMeans(df)
  names(rowm) <- c(rep("Ctrl", times=8), rep("Psi3d", times=8), rep("Ket3d", times=7), rep("Psi1d", times=7), rep("Ket1d", times=5))
  rowm <- as.data.frame(rowm)
  rowm$group <- c(rep("Ctrl", times=8), rep("Psi3d", times=8), rep("Ket3d", times=7), rep("Psi1d", times=7), rep("Ket1d", times=5))
  p <- mutate(rowm, group=factor(group,ordered=T, c("Ctrl", "Psi1d", "Ket1d", "Psi3d", "Ket3d")))
  y <- aggregate(p[, 1], list(p$group), mean)
  se <- aggregate(p[, 1], list(p$group), sd)

  df <- data.frame(group=ordered(c("Ctrl", "Psi3d", "Ket3d"), levels=c("Ctrl",  "Psi3d", "Ket3d")), TPM=y$x[c(1,4,5)], se=se$x[c(1,4,5)])
  print(
    ggplot(NULL,  aes(x= as.numeric(group)))+ 
      geom_smooth(data=df, aes(as.numeric(group), TPM, ymin = TPM - se, ymax = TPM + se), stat="identity", col="red")+
      scale_x_discrete(limits=c("Ctrl", "Psi3d", "Ket3d")) +
      scale_y_log10()+ 
      theme_classic(base_size = 24)+
      theme(legend.title=element_blank(), axis.title.x = element_blank(), axis.text = element_text(size=30), axis.title.y = element_text(size=30))+
      ylab("TPM")+
      coord_cartesian(xlim = c(1,3.2), expand = FALSE)
  )
}
```


```{r, fig.show='hide'}
Fig3F1 <- GO_smooth_line_plot_3d(TPM, sigGenes_up)+
  scale_x_discrete(limits=c("Ctrl", "Psi3d", "Ket3d"),
                   labels=c("Ctrl", "3d Psi", "3d Ket"))
```

```{r}
sigGenes_down <- res %>% as.data.frame() %>% filter(padj<0.05) %>% 
  filter(log2FoldChange<0) %>% rownames() %>% substr(1, 15)
```

Number of genes: `r length(sigGenes_down)`

```{r, fig.show='hide'}
Fig3F2 <- GO_smooth_line_plot_3d(TPM, sigGenes_down)+
  scale_x_discrete(limits=c("Ctrl", "Psi3d", "Ket3d"),
                   labels=c("Ctrl", "3d Psi", "3d Ket"))
```

```{r,fig.asp=0.26, fig.width=8.8}
Fig3F1+Fig3F2&
  theme(axis.text = element_text(color="black", size=20),
        axis.title.y = element_text(size=20))
```

```{r}
sessionInfo()
```